version: '3.8'

services:
  webapp:
    image: straighten/straighten:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
      - ./certs:/https:ro
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/var/sqlite

volumes:
  sqlite-data:
