version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./certs:/https:ro
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/var/sqlite

volumes:
  sqlite-data:
