version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
      - 443:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./certs:/https:ro
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/var/sqlite

volumes:
  sqlite-data:
